CREATE TABLE schools (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    schoolName VARCHAR(255) UNIQUE NOT NULL,
    address VARCHAR(255) NOT NULL,
    contact_number VARCHAR(255) NOT NULL,
    school_type VARCHAR(255) NOT NULL,
    grade_level VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    owner_id BIGINT NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE
);