version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: haazer_db
      MYSQL_USER: hazer-user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Refers to the volume below

  keycloak:
    image: jboss/keycloak:25.0.0
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_ENABLED=true  # 👈 This allows HTTP
      - KC_PROXY=edge  # 👈 Necessary if behind a reverse proxy
    command: start-dev

volumes:
  mysql_data:
