# ? Keycloak Configuration (Use Public IP)
quarkus.oidc.auth-server-url=https://171.22.26.114:8443/realms/haazer-realm
quarkus.oidc.client-id=haazer-app
quarkus.oidc.credentials.secret=klBS235ii9clLb6pl9JjOh5uZAOUWyGl
quarkus.oidc.token-path=https://171.22.26.114:8443/realms/haazer-realm/protocol/openid-connect/token
keycloak.admin-url=https://171.22.26.114:8443/admin/realms/haazer-realm/users
quarkus.oidc.token-path-master=https://171.22.26.114:8443/realms/master/protocol/openid-connect/token

# ? Admin Keycloak Configuration
quarkus.keycloak.admin-client-id=admin-cli
quarkus.keycloak.admin-username=admin
quarkus.keycloak.admin-password=admin

# ? MySQL Database Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=hazer-app
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:mysql://mysql:3306/haazer_db

# ? Flyway Configuration
quarkus.flyway.migrate-at-start=true
quarkus.flyway.enabled=true
quarkus.flyway.locations=classpath:db/migration

# ? Hibernate Settings for Schema Generation
quarkus.hibernate-orm.database.generation=update

# ? Swagger Settings
quarkus.smallrye-openapi.path=/swagger-docs
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

# ? HTTP Configuration (Expose Correct Port)
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

# ? Docker Build Options
quarkus.container-image.build=true
quarkus.container-image.name=hazer
quarkus.container-image.tag=latest
quarkus.jib.ports=8080
