services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: haazer_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Refers to the volume below

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak
    restart: always
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: 1234
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/haazer_db
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
