CREATE TABLE teacher (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    createdAt VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    field VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id)
);